trigger:
- main

pool:
  name: 'dgiiexam'  # Este es un agente self-hosted

variables:
  imageName: 'hello-world-image'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Crea la imagen de Docker
- task: Docker@2
  inputs:
    containerRegistry: 'dgiiexam'         # Asegúrate de que esté bien definido como service connection
    repository: 'hello-world'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      latest

# Ejecuta la imagen recién creada
- script: |
    docker run -d -p 5000:5000 hello-world:latest
  displayName: "Run Docker Container"
