trigger:
- main

pool:
  #vmImage: 'ubuntu-latest'
  name: 'dgiiexam'  # Este es un agente self-hosted. No logre ponerlo a funcionar con Azure. No tiene habil la opcion de paralelismo entre servicios.

variables:
  imageName: 'hello-world-image' #imagen de docker que imprimira Hola Mundo

steps:
- task: UsePythonVersion@0 #que aplicativo imprimira el mensaje, para este caso Python
  inputs:
    versionSpec: '3.x'

- script: | #script para instalar python
    python -m pip install --upgrade pip 
    pip install -r requirements.txt
  displayName: 'Install dependencies'


- task: Docker@2 # Crea la imagen de Docker
  inputs:
    containerRegistry: 'dgiiexam'
    repository: 'hello-world'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      latest
