trigger:
- main

pool:
  name: 'dgiiexam'  # Este es un agente self-hosted. No logre ponerlo a funcionar con Azure. No tiene habil la opcion de paralelismo entre servicios.

variables:
  imageName: 'hello-world-image'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Crea la imagen de Docker
- task: Docker@2
  inputs:
    containerRegistry: 'dgiiexam'
    repository: 'hello-world'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      latest
